name: "Build python environment"
description: "Download the specified python version and build the venv according to the requirements/constraints"

inputs:
  python_version:
    description:  "Python version of the virtual environment"
    required: true
    default: 3.10
  requirements_file:
    description: "Requirements file listing the packages"
    required: true
    default: requirements.txt
  constraints_file:
    description: "Constraints file listing the package constraints"
    required: true
    default: constraints.txt
  requirements:
    description: "Package versions to be installed in the venv"
  constraints:
    description: "Constraints on individual package versions"
  run:
    description: "Shell command to be ran inside the venv"

runs:
  using: "composite"
  steps:
    - name: "Downloads and sets up python"
      uses: actions/setup-python@v4
      with:
        python-version:  ${{inputs.python_version}}
    - name: "Creates and starts the virtual environment"
      shell: bash
      run: |
        python -m venv venv
        . venv/bin/activate
        echo "PATH=$PATH:$VIRTUAL_ENV/bin" >> $GITHUB_ENV
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        which python
    - name: "Installs the required packages"
      shell: bash
      run: |
        echo ${{inputs.requirements}} >> ${{inputs.requirements_file}}
        echo ${{inputs.constraints}} >> ${{inputs.constraints_file}}
        which python
        pip install -r ${{inputs.requirements_file}} -c ${{inputs.constraints_file}}
    - name: "Runs the shell script"
      shell: bash
      run: ${{inputs.run}}

    
